-- VERDICT: JPM SUPREMACY (896B+ MCAP)
-- MISSION: EmploymentMission2026 (São Paulo Leadership)
SELECT 
    TICKER,
    CASE 
        WHEN TICKER = 'JPM' THEN '>>> GLOBAL WINNER (SUPREME)'
        WHEN TICKER = 'ITUB' THEN 'LATAM MOMENTUM CHAMPION'
        ELSE 'SUPPORTING CLUSTER'
    END AS STATUS
FROM Stargate_EOD_Truth
ORDER BY CLOSE_PRICE DESC;
